language: c

sudo: false

cache:
  directories:
    - ~/.cabal/packages
    - ~/.cabal/store

matrix:
  include:
    - env: CABALVER=3.0 GHCVER=8.6.5
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.6.5], sources: [hvr-ghc]}}
    - env: CABALVER=3.0 GHCVER=8.8.3
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.8.3], sources: [hvr-ghc]}}
    - env: CABALVER=3.0 GHCVER=8.10.1
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.10.1], sources: [hvr-ghc]}}

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - cabal --version
  - ghc --version
  - travis_retry cabal new-update

script:
  # To avoid re-compilation it is important to use exactly the same
  # configuration for all steps.
  - export CONFIG="--enable-tests --enable-benchmarks --flags=dev"
  - cabal format
  - pushd parser-combinators-tests && cabal format && popd
  - git diff --exit-code --color=always
  - cabal new-build all $CONFIG
  - cabal new-test all $CONFIG
  - cabal new-haddock parser-combinators $CONFIG
  # - cabal new-haddock parser-combinators-tests $CONFIG
  - cabal new-sdist
  - pushd parser-combinators-tests && cabal new-sdist && popd

notifications:
  email: false
